name: Build & Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build
        runs: { using: docker, image: Dockerfile }

      - name: Public artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build Artifact
          path: out/
