name: Build & Test
on:
 - push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make nasm binutils binutils-aarch64-linux-gnu

      - name: Build via Makefile
        run: make ci_build

      - name: Public artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build Artifact
          path: out/

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y nasm

      - name: Run Tests
        run: echo "TODO"